CREATE DATABASE DBCLINICAMEDICA;

USE DBCLINICAMEDICA;

CREATE TABLE ENDERECO(
	IDENDERECO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(100),
    NUMERO INT,
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(100),
    ESTADO CHAR(2),
    CEP VARCHAR(8)
);

CREATE TABLE PACIENTE(
	IDPACIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(150),
    CPF VARCHAR(11),
    TELEFONE VARCHAR(11),
    CELULAR VARCHAR(11),
    EMAIL VARCHAR(100),
    IDENDERECO INT NOT NULL,
    FOREIGN KEY (IDENDERECO) REFERENCES ENDERECO (IDENDERECO)
);

CREATE TABLE MEDICO(
	IDMEDICO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(150),
    CPF VARCHAR(11),
    TELEFONE VARCHAR(11),
    CELULAR VARCHAR(11),
    IDENDERECO INT NOT NULL,
    EMAIL VARCHAR(100),
    CRM VARCHAR(13),
    FOREIGN KEY (IDENDERECO) REFERENCES ENDERECO (IDENDERECO)
);

CREATE TABLE CONSULTA(
	IDCONSULTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DATA_CONSULTA DATETIME,
	IDPACIENTE INT NOT NULL,
	IDMEDICO INT NOT NULL,
	FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE (IDPACIENTE),
	FOREIGN KEY (IDMEDICO) REFERENCES MEDICO (IDMEDICO)
);

CREATE TABLE PRONTUARIO(
	IDPRONTUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDCLIENTE INT NOT NULL,
	ANAMNESE VARCHAR(1000),
	LAUDOS VARCHAR(1000),
	DIAGNOSTICOS VARCHAR(1000),
	PRESCRICOES VARCHAR(1000),
	ATESTADOS VARCHAR(1000),
	
);

CREATE TABLE USUARIO(
	IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	LOGIN VARCHAR(45),
	SENHA VARCHAR(12),
	TIPO VARCHAR(100)
);

INSERT INTO USUARIO (TIPO) VALUES ("ADMINISTRADOR");
INSERT INTO USUARIO (TIPO) VALUES ("MÉDICO");
INSERT INTO USUARIO (TIPO) VALUES ("RECEPCIONISTA");