DROP DATABASE IF EXISTS DBCLINICAMEDICA;

CREATE DATABASE DBCLINICAMEDICA;

USE DBCLINICAMEDICA;

CREATE TABLE ENDERECO(
	IDENDERECO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(100),
    NUMERO INT,
    BAIRRO VARCHAR(100),
    CIDADE VARCHAR(100),
    ESTADO CHAR(2),
    CEP VARCHAR(8)
);

CREATE TABLE PACIENTE(
	IDPACIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(150),
    CPF VARCHAR(11),
    TELEFONE VARCHAR(11),
    CELULAR VARCHAR(11),
    EMAIL VARCHAR(100),
    IDENDERECO INT,
    FOREIGN KEY (IDENDERECO) REFERENCES ENDERECO (IDENDERECO)
);

CREATE TABLE MEDICO(
	IDMEDICO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(150),
    CPF VARCHAR(11),
    TELEFONE VARCHAR(11),
    CELULAR VARCHAR(11),
    IDENDERECO INT,
    EMAIL VARCHAR(100),
    CRM VARCHAR(13),
    ESPECIALIDADE VARCHAR(100),
    USUARIO VARCHAR(45),
    SENHA VARCHAR(45),
    ADMIN BOOLEAN,
    FOREIGN KEY (IDENDERECO) REFERENCES ENDERECO (IDENDERECO)
);

CREATE TABLE CONSULTA(
	IDCONSULTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DATA_CONSULTA DATETIME,
	IDPACIENTE INT NOT NULL,
	IDMEDICO INT NOT NULL,
	IDRECEPCIONISTA INT NOT NULL,
	FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE (IDPACIENTE),
	FOREIGN KEY (IDMEDICO) REFERENCES MEDICO (IDMEDICO)
);

CREATE TABLE PRONTUARIO(
	IDPRONTUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDPACIENTE INT NOT NULL,
	IDMEDICO INT NOT NULL,
	OBSERVACOES VARCHAR(1000),
	FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE (IDPACIENTE),
	FOREIGN KEY (IDMEDICO) REFERENCES MEDICO (IDMEDICO)
);

INSERT INTO MEDICO (USUARIO, SENHA, ADMIN) VALUES ("root", "root", TRUE);